waterbutler/providers/cloudfiles/provider.py
When using internal urls if accept_url is passed into download make sure to return a public url
=> [Feature] Fix use_public and accept_url in cloudfiles download

.travis.yml, tasks.py
persistent wheelhouse cache/auto update
=> [feature] wheelhouse

waterbutler/providers/googledrive/metadata.py, waterbutler/providers/googledrive/provider.py, waterbutler/providers/googledrive/utils.py
Detect file extensions for Google Docs files. Append appropriate pseudo-extension to file names; download using appropriate export links.
=> Handle docs extensions

tests/providers/dropbox/test_provider.py, tests/providers/googledrive/fixtures.py, tests/providers/googledrive/test_metadata.py, tests/providers/googledrive/test_provider.py, waterbutler/providers/googledrive/provider.py
aw yiss
```
-------------------------------------------------- coverage: platform darwin, python 3.4.2-final-0 ---------------------------------------------------
Name                                         Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------
waterbutler/providers/googledrive/__init__       1      0   100%
waterbutler/providers/googledrive/metadata      51      2    96%   58-59
waterbutler/providers/googledrive/provider     123      1    99%   193
waterbutler/providers/googledrive/settings       7      2    71%   3-4
waterbutler/providers/googledrive/utils         18      1    94%   34
--------------------------------------------------------------------------
TOTAL                                          200      6 …
```
=> Google Drive tests

tests/providers/box/test_provider.py, waterbutler/providers/box/provider.py
* More tests
* Handle revisions for non-premium accounts
=> Box tests and fixes

README.md
=> Update readme to reflect removel of duel servers

tests/providers/github/test_provider.py, waterbutler/providers/github/provider.py, waterbutler/server/api/v1/provider/movecopy.py
This branch fixes two separate bugs affecting renaming on GitHub and S3
Fixes: [#OSF-4676]
=> [CR] Fix 500s when renaming on S3 and GitHub

waterbutler/server/api/v1/provider/__init__.py
delete actions don't set self.target_path
=> v1: don't use target_path for delete logging

README.md, waterbutler/auth/osf/settings.py, waterbutler/server/settings.py
=> [CR] prefer localhost to 127.0.0.1 to match OSF

README.md, docs/settingup.rst
I added the steps to setup correctly the invoke command.
=> Update the docs to correctly setup the waterbutler environment.

waterbutler/providers/github/provider.py
[OSF-5774](https://openscience.atlassian.net/browse/OSF-5774)
Reduce overhead by replacing tree with GIT_EMPTY_SHA instead of deleting children
update rwaterbutler/providers/github/provider.py def _delete_root_folder_contents for GIT_EMPTY_SHA
None
After much testing it appears that there is no requirement for a .gitkeep file in the empty repository
#OSF-5774
=> [RFR][Feature]OSF-5774 Update _delete_folder_contents to replace sha instead of deleting children

tests/providers/box/test_provider.py, waterbutler/providers/box/provider.py
[OSF-6050](https://openscience.atlassian.net/browse/OSF-6050)
Update Box provider to "limit=1000" for "Get Folder's Items" call
update waterbutler/providers/box/provider.py for limit=1000
update tests/providers/box/test_provider.py test TestMetadata.test_metadata for registered url
None
##ToDo
Implement paging
#OSF-5847
=> [OSF-6050][HOTFIX]Update Box provider to "limit=1000" for "Get Folder's Items" call

waterbutler/server/app.py
"docker-compose stop" sends SIGTERM.
This PR catches and handles the SIGTERM signal.
Update waterbutler/server/app.py
- Add catch for SIGTERM during server creation
- Add def sig_handler to exit gracefully
None
[#SVCS-370]
=> Catch SIGTERM and exit gracefully

PULL_REQUEST_TEMPLATE.md
https://openscience.atlassian.net/browse/SVCS-542
https://github.com/CenterForOpenScience/modular-file-renderer/pull/287
Add PR Template to help the reviewing progress.
Add `PULL_REQUEST_TEMPLATE.md` to the root directory.
No
No
No
=> [SVCS-542] Add PR Template for WB

tests/auth/osf/test_handler.py, waterbutler/auth/osf/handler.py, waterbutler/core/auth.py, waterbutler/core/exceptions.py, waterbutler/server/api/v1/provider/__init__.py, waterbutler/server/api/v1/provider/movecopy.py, waterbutler/server/auth.py
https://openscience.atlassian.net/browse/SVCS-550
Currently you cannot issue POST requests to a public project to copy from that project. This PR allows copying from public projects into your own project
method = POST now asks for read permissions. Later on in the `move_or_copy` it asks for read/write permissions based on the body parameters of the request.
```python
copy = copyfrom
rename = upload
move = upload
```
If done properly there should be no side-effects. More in test notes
More indepth analysis on JIRA ticket.
Due to the security problems that errors in this PR could cause, testing everything related to POST requests are needed.
There is a postman collection on the JIRA ticket that will help get started with testing.
Things to test:
move/copy/rename within a project (all should …
=> [SVCS-550] Allow copy requests to public resources

waterbutler/providers/googlecloud/provider.py
https://openscience.atlassian.net/browse/SVCS-697
Delay URL Build/Sign for GoogleCloud.
For more information, refer to the JIRA ticket and Sentry errors.
Use `functool.partial()` to delay building and signing URL until the request is actually made.
No
Dev QA only. Monitor the Sentry for errors.
No
=> [HotFix] [SVCS-697] Delay URL Build/Sign for GoogleCloud

tests/providers/osfstorage/fixtures.py, waterbutler/providers/osfstorage/provider.py
=> [No Ticket] Disable intra move/copy region check for filesystem

docs/waterbutler.core.streams.rst, tests/core/streams/test_cutoffstream.py, tests/providers/figshare/fixtures.py, waterbutler/core/streams/__init__.py, waterbutler/core/streams/base.py, waterbutler/providers/figshare/provider.py, waterbutler/providers/googledrive/provider.py
https://openscience.atlassian.net/browse/SVCS-424
Fix figshare uploads and support future multi-part uploads.
See commit messages.
None expected.
Please test regular computer-to-figshare uploads and cross-provider move/copies to figshare, too.
None needed.
Fixes: #306 
Needed-by: #325, #347, #348
=> [CR][SVCS-424] Figshare upload fix / chunked upload support

tasks.py
No
Improve The Command `invoke test`
- Add an option `--provider=` to test a specific provider only
- Add an option `--path=` to test a specific file or folder only
- Add an option `--nocov=` to disable coverage
No
No
No
=> [No-Ticket] Improve The Command `invoke test`

waterbutler/providers/dropbox/provider.py
https://openscience.atlassian.net/browse/SVCS-913
A bug was introduced during dropbox chunked upload where the argument `conflict` is not passed along from `_upload()`to `_contiguous_upload()` and `_chunked_upload()`. This bug led to all requests made to the dropbox upload API missing the `mode` parameter in the required header `Dropbox-API-Arg`.
See https://github.com/CenterForOpenScience/waterbutler/pull/347/files#diff-c3a345e63f19827819cde3a30cae89d6L262 and 
https://github.com/CenterForOpenScience/waterbutler/pull/347/files#diff-c3a345e63f19827819cde3a30cae89d6L255
* `_contiguous_upload()` now takes in the `conflict` argument from `_upload()`
* `_chunked_upload()` now takes in the `conflict` argument from `_upload()` and passed along to the `_complete_session()`
* Move `path_arg` from …
=> [HotFix] [SVCS-913] Fix Conflict Handling For Dropbox Contiguous Upload

waterbutler/providers/s3/provider.py
https://github.com/CenterForOpenScience/osf.io/pull/10414/
To allow water butler to accept different paths as the root folder, not just the bucket route.This uses the `settings`  JSON to pass information about the users root folder, infomation sent via the path will not change, but the user will now have a base root folder that will be their `folder_id`, which currently is always their bucket name. 
- Extra logic to allow for bucket setting to be used.
- Excludes parent file from results.
N/A
See QA plans in project notion
To test this I wrote my own docker-compose:
```
version: '3.4'
volumes:
wb_requirements_vol:
external: false
wb_requirements_local_bin_vol:
external: false
wb_tmp_vol:
external: false
osfstoragecache_vol:
external: false
rabbitmq_vol:
external: false
services: …
```
=> [ENG-4579] Allow the base folder to not be a bucket for S3

waterbutler/providers/s3/provider.py
https://openscience.atlassian.net/browse/ENG-4579
Allow path for s3 addon to be set with a base folder. so only part a of a bucket is selectable
-  Change the path given to match the S3 prefix
-  Change the path given correct for path validation
=> [ENG-4579] S3 Improvement Changes for WB

tests/providers/s3/test_provider.py, waterbutler/providers/s3/provider.py
https://openscience.atlassian.net/browse/ENG-4615
Add test coverage for new s3 improvement changes.
- adds tests and minor clean-up
none that I know of.
=> [ENG-4615] Add unittests s3 improvement

.github/workflows/test-build.yml, dev-requirements.txt, requirements.txt
[[ENG-7520]](https://openscience.atlassian.net/browse/ENG-7520)
Fixup Github Actions to start to run
[ENG-7520]: https://openscience.atlassian.net/browse/ENG-7520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-7520] | updated test-build.yml to be compatible with python 3.13

requirements.txt, setup.py, waterbutler/core/exceptions.py, waterbutler/core/path.py, waterbutler/core/provider.py, waterbutler/core/remote_logging.py, waterbutler/providers/bitbucket/provider.py, waterbutler/providers/box/provider.py, waterbutler/providers/cloudfiles/provider.py, waterbutler/providers/dataverse/provider.py, waterbutler/providers/dropbox/provider.py, waterbutler/providers/figshare/provider.py, waterbutler/providers/filesystem/provider.py, waterbutler/providers/github/provider.py, waterbutler/providers/gitlab/provider.py, waterbutler/providers/googlecloud/provider.py, waterbutler/providers/googlecloud/utils.py, waterbutler/providers/googledrive/provider.py, waterbutler/providers/onedrive/provider.py, waterbutler/providers/osfstorage/provider.py, waterbutler/providers/s3/provider.py, waterbutler/server/api/v1/core.py, waterbutler/server/api/v1/provider/__init__.py
https://openscience.atlassian.net/browse/ENG-7518
Update python code for python3.13 compatibility. Should pass python compile check (python3 -m compileall -q .)
Update code to pass check (python3 -m compileall -q .) 
,
update code style to be it suitable with 3.13 python version related linters (it looks more strict than in previous versions) and allow to run unit tests.
=> [ENG-7518] Update python code for python3.13 compatibility

dev-requirements.txt
[ENG-7522](https://openscience.atlassian.net/browse/ENG-7522)
Update dependencies in dep-group "dev"
The dep-group tickets are about updating a batch of dependencies at a time. In the WB requirements DB, column C is "group". When we take on a dep-group ticket, we're trying to upgrade all the tickets in that group to their latest version.
[ENG-7522]: https://openscience.atlassian.net/browse/ENG-7522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-7522] | Updated Dep-group 2 to latest versions

requirements.txt
https://openscience.atlassian.net/browse/ENG-7521
2.3.1 BE: WB Dep-group 1: async+auth
Update dependencies in dep-groups "async" & "auth" 
(in previous PRs were added up-to-date packages versions so there is a few changes )
checking consistency of osf and wb interaction on python 3.13 version by executing unittesting scenarious
python3 -m pytest tests/test_addons.py
`
invoke test
todo: need update in future on prod(staging testing) lib boto to boto3 and related codebase
=> [ENG-7521] 2.3.1 BE: WB Dep-group 1: async+auth

requirements.txt, waterbutler/providers/bitbucket/metadata.py, waterbutler/providers/github/provider.py
https://openscience.atlassian.net/browse/ENG-7524
Update dependencies in dep-group "infra"
Update dependencies in dep-group "infra"
also have seen some another strict restriction in Qodana code inspection so updated it too
=> [ENG-7524] 2.3.4 BE: WB Dep-group 4: infra

tasks.py
=> ENG-7526 | fixed WB Dockerfile builds successfully

tests/core/test_utils.py, tests/providers/dataverse/test_provider.py, tests/providers/figshare/test_metadata.py, tests/providers/figshare/test_provider.py, tests/providers/gitlab/test_provider.py, tests/providers/s3/fixtures.py, tests/providers/s3/test_provider.py, tests/server/api/v1/test_create_mixin.py, waterbutler/auth/osf/handler.py, waterbutler/core/streams/__init__.py, waterbutler/core/streams/http.py, waterbutler/providers/dataverse/provider.py, waterbutler/providers/s3/metadata.py, waterbutler/providers/s3/provider.py
https://openscience.atlassian.net/browse/ENG-8054
WB has a bunch of failing tests. Let's fix 'em!
If the cause of a test failure turns out to need a big fix, we can create another ticket to track it.
it was a base ticket (https://github.com/CenterForOpenScience/waterbutler/pull/437 ) , Fitz and I have added another updates, need to deal with S3 tests as well.
=> [ENG-8054] Fix buff worms tests v2

poetry.lock, pyproject.toml, tests/server/api/v1/test_create_mixin.py, tests/server/api/v1/utils.py
=> [ENG-7884] | Add Autoformatting tools and configuration to WB

tests/server/api/v0/test_crud.py, waterbutler/server/api/v0/crud.py
=> [ENG-8252] | Fix failing test_upload test

tests/tasks/test_copy.py, tests/tasks/test_move.py
=> [ENG-8251] | Fix failing move/copy task tests

tests/tasks/test_serialization.py, waterbutler/core/metadata.py, waterbutler/providers/bitbucket/metadata.py, waterbutler/providers/box/metadata.py, waterbutler/providers/cloudfiles/metadata.py, waterbutler/providers/dataverse/metadata.py, waterbutler/providers/dropbox/metadata.py, waterbutler/providers/figshare/metadata.py, waterbutler/providers/filesystem/metadata.py, waterbutler/providers/github/metadata.py, waterbutler/providers/gitlab/metadata.py, waterbutler/providers/googledrive/metadata.py, waterbutler/providers/onedrive/metadata.py, waterbutler/providers/osfstorage/metadata.py, waterbutler/providers/owncloud/metadata.py, waterbutler/providers/s3/metadata.py, waterbutler/tasks/app.py, waterbutler/tasks/serialization.py
=> [ENG-8071] | Unskip move/copy task tests, Fix Failing serialization tests

tests/tasks/test_serialization.py, waterbutler/core/metadata.py, waterbutler/providers/bitbucket/metadata.py, waterbutler/providers/box/metadata.py, waterbutler/providers/cloudfiles/metadata.py, waterbutler/providers/dataverse/metadata.py, waterbutler/providers/dropbox/metadata.py, waterbutler/providers/figshare/metadata.py, waterbutler/providers/filesystem/metadata.py, waterbutler/providers/github/metadata.py, waterbutler/providers/gitlab/metadata.py, waterbutler/providers/googledrive/metadata.py, waterbutler/providers/onedrive/metadata.py, waterbutler/providers/osfstorage/metadata.py, waterbutler/providers/owncloud/metadata.py, waterbutler/providers/s3/metadata.py, waterbutler/tasks/app.py, waterbutler/tasks/serialization.py
=> [ENG-8071] | updated serialization.py to support metadata

tests/providers/dataverse/test_provider.py, waterbutler/providers/dataverse/provider.py
=> [ENG-8456] 2.5.18 BE: WB stop double encoding revisions in dataverse

waterbutler/core/metadata.py, waterbutler/core/utils.py
=> [ENG-8457] | Fix broken copy folder to osfstorage issue

waterbutler/core/provider.py
https://openscience.atlassian.net/browse/ENG-8413?atlOrigin=eyJpIjoiZWFmZDI2MTdjYTIyNDcyZmJlZWNlOGQ2YzkzYzk2ZjEiLCJwIjoiaiJ9
=> [ENG-8413] Fix double encoding spaces in furl

waterbutler/providers/s3/provider.py
=> [ENG-8483] Fix redundant is_async parameter

docs/conf.py, docs/gettingstarted.rst, readthedocs.yml, waterbutler/providers/s3/provider.py
https://openscience.atlassian.net/browse/ENG-8425?atlOrigin=eyJpIjoiZDRlZTBiN2VlMjAzNDI2Njg0MjdlOTIyMmNiYWQ3ZTYiLCJwIjoiaiJ9
=> [ENG-8425] Update WB docs

waterbutler/providers/azureblobstorage/provider.py
This commit fixed the blob listing issue at the container root
=> fix blob listing issue at container root
