CenterForOpenScience/waterbutler

waterbutler/providers/box/metadata.py
waterbutler/providers/box/provider.py

Purpose
=======
Add Box to the supported providers for waterbutler
Accompanies: https://github.com/CenterForOpenScience/osf.io/pull/1758
Changes
=======
* Box support added
* FormData added to utils (from @chrisseto )
Side Effects
=========
* Theoretically possible for a user to intercept outgoing requests, edit the id, and gain access to an authorizer's files that aren't in the shared directory

Box Provider

---

tests/providers/figshare/test_provider.py
waterbutler/providers/figshare/provider.py

The Figshare API allows deleting public files, which shouldn't be deletable. On delete, send a metadata request, and bail out if file is public. We wrote to the Figshare team about this, but for now, disabling deletion on these files is probably safest.
@chrisseto

Prevent deletion of public files.

---

tests/providers/figshare/test_provider.py
waterbutler/providers/figshare/metadata.py
waterbutler/providers/figshare/provider.py

Second attempt to handle figshare deletes. Based on correspondence with the figshare lead, it is actually possible to delete public / published files, but only when the file being deleted is not the last file in the fileset. This patch adds a `canDelete` field to the figshare file metadata indicating whether the file can be deleted.

Add canDelete field to figshare extra metadata.

---

tests/providers/github/test_provider.py
waterbutler/providers/github/provider.py

- Fixes incorrect GitHub view URLs from being built on the OSF files page.
- Uses GitHub's ```html_url``` as the web view URL for file metadata not retrieved from the git trees API, continues to build URLs for file metadata that is retrieved by the git trees API.

GitHub View URLs

---

tests/providers/osfstorage/test_provider.py
waterbutler/providers/osfstorage/metadata.py
waterbutler/providers/osfstorage/provider.py

Allow API to grab md5 + sha256 hashes, and also so that the osf can grab and use them.
This accompanies OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/3517 and needs to be merged together for either to work.
md5 information is added to the metadata extra section of revision and file classes

Add hashes metadata

---

README.md
tests/core/test_metadata.py
tests/server/api/v1/test_create_mixin.py
tests/utils.py
waterbutler/core/metadata.py
waterbutler/server/api/v1/provider/create.py
waterbutler/server/api/v1/provider/metadata.py
waterbutler/server/api/v1/provider/movecopy.py
waterbutler/server/settings.py

Via: [#OSF-4667]
WaterButler was sending back responses in its own format, whereas the OSF tries to adhere to JSON-API formatted responses.  This patch updates the v1 endpoints to return JSON-API compliant responses on success.  It does **not** fix the error responses from JSON-API.  
I've also opted to drop the included '?kind=folder' query param from the `new_folder` link.  It's already documented in the BAPI docs as a required parameter, and would probably be more appropriate as a `meta` entry.  If it's still desired, it's a quick patch to put it back.
Cheers,
Fitz

[CR] Update waterbutler to return JSON-API compliant 

---

waterbutler/providers/osfstorage/provider.py

move/copy response status should be 201 if a new resource is created or
200 if an existing resource is overwritten.  copy was already doing
this, move now does the same
[#OSF-4755]

[CR] v1: fix move response status from osfstorage

---

waterbutler/providers/github/provider.py

Folders (trees) in GitHub cannot be operated on directly, and must
instead be moved/renamed/deleted by manipulating the blob paths in the
master tree.  Unfortunately, GH truncates master tree listings for repos
with lots of files and does not provide a way to page through and
retrieve all entries. Any blobs omitted when updating the master tree
will be treated as deleted.  Therefore, it doesn't seem that we can
always safely perform certain folder ops on large repos, so instead we
throw a 501 Not Implemented with an explanatory message.
Fixes [#OSF-4867]

[CR] github: avoid dataloss w/ folderops in large repos

---

tests/server/api/v1/test_create_mixin.py
waterbutler/server/api/v1/provider/create.py

We had been returning 400.  All other actions,kind combos are legit.
Minor change, no JIRA ticket created.

[CR] return 409 when trying to create a folder on a fileish path

---

tests/core/test_metadata.py
waterbutler/core/metadata.py

Restore `?kind=folder` to new_folder action, `?kind=file` to upload
action, and remove any null actions from response
[#OSF-4845]

[CR] jsonapi: restore kind= to actions + prune nulls

---

tests/providers/dropbox/test_provider.py
tests/providers/osfstorage/test_provider.py
tests/providers/s3/test_provider.py
waterbutler/providers/osfstorage/provider.py

This CR fixes broken tests in the osfstorage, dropbox, and s3 providers, related to the [changes in commit b5b742cb](https://github.com/CenterForOpenScience/aiohttpretty/commit/b5b742cba4e3d1e6b883f122f2b621219a781833) in aiohttpretty.
To test this, run `pip install -U -r dev-requirements` in the WB directory to get the most recent version of aiohttpretty.  Then run `invoke test` and behold all the lovely failures.  Then checkout this PR, rerun the tests, and wallow in an enchanting sea of passing green.

[CR] fix broken tests from aiohttpretty upgrade

---

tests/providers/s3/test_provider.py
waterbutler/providers/s3/provider.py

If you try to delete a non-empty folder stored in s3, you will get a successful response (204 No Content), but neither the folder nor its contents will be deleted.
This PR implements recursive delete for the Amazon S3 provider.   Amazon doesn't treat folders as first-class objects, so recursively deleting a folder means deleting all of its child files.  Both the file list action and bulk delete action are limited to 1000 entries, so we must supported making successive requests.
Fixes [#OSF-4881]
Create a folder on s3 with at least one file in it.  Try to run a DELETE against that folder's delete action.
Both folder and child file are deleted.
Both folder and child file survive the ordeal.
No survivors.

[CR] implement recursive delete for S3 folders

---

waterbutler/providers/github/provider.py

When moving files from a non-root folder in github, the source file was  being left behind.  This was because the tree entry for the source directory was left in the modified master tree, where it still contained references to the old blob/tree.  The solution was to remove all tree entries from the master tree and to allow github to infer the new tree structure from the path names of the remaining blobs.
I also included a fix for folder move/copy actions returning the wrong status code, since the changes are very closely related.
Fixes: [#OSF-4792], [#OSF-4870]

[CR] github: don't leave behind source file when moving

---

tests/providers/box/test_provider.py
waterbutler/providers/box/provider.py
waterbutler/providers/osfstorage/provider.py
waterbutler/server/api/v1/provider/__init__.py

Problem
--
Create and delete actions via WaterButler v1 API are not being logged by the OSF.  Example:
I issue a PUT against the WB v1 API to create a new folder, "pr-example", under osfstorage:
... and it succeeds.  But when I visit the node's page, I can see the folder in the file browser, but no entry in the node logs:
The same is true for delete actions.
Testing
--
Run create folder, create file, and delete actions against waterbutler.  All actions should show up in the node logs on the OSF side.
Fixes: [#OSF-5148]

[CR] repair logging for Waterbutler delete/create actions

---

tests/providers/box/test_provider.py
tests/providers/dataverse/test_provider.py
tests/providers/dropbox/test_provider.py
tests/providers/filesystem/test_provider.py
tests/providers/github/test_provider.py
tests/providers/googledrive/test_provider.py
tests/providers/osfstorage/test_provider.py
tests/providers/s3/test_provider.py
tests/server/api/v1/test_create_mixin.py
tests/utils.py
waterbutler/core/provider.py
waterbutler/providers/box/provider.py
waterbutler/providers/cloudfiles/provider.py
waterbutler/providers/dataverse/provider.py
waterbutler/providers/dropbox/provider.py
waterbutler/providers/figshare/provider.py
waterbutler/providers/filesystem/provider.py
waterbutler/providers/github/provider.py
waterbutler/providers/googledrive/provider.py
waterbutler/providers/osfstorage/provider.py
waterbutler/providers/s3/provider.py
waterbutler/server/api/v1/provider/__init__.py
waterbutler/server/api/v1/provider/create.py
waterbutler/server/api/v1/provider/movecopy.py

v1 expects folder paths to always end with a slash and file paths to never end with a slash.  However, it wasn't enforcing this and some manually-constructed tests were 500ing as a result.  It was decided
that trying to address folders as file and vice-versa should consistently produce 404s.
[#OSF-4675]

[CR] always 404 on file/folder path mismatch

---

tests/providers/github/test_provider.py
waterbutler/providers/github/provider.py

Every path part of a GithubPath should have an id tuple of ($branch,
$ref?).  The WaterButler Path object was not providing the branch when
creating a subentity via the child() method.  Fixed that.
Fixes [#OSF-5261].

v1: GitHubPath should propagate branch to children

---

waterbutler/providers/s3/provider.py

Recursive delete in S3 is done with an XML payload.  When one of the
files or folders to be deleted has an ampersand in the name, the payload
fails validation with Amazon.  Escape all folder and filenames in the
payload to avoid this.
Fixes: [#OSF-5269]

s3: fix recursive delete when '&' is in paths

---

tests/providers/box/test_provider.py
waterbutler/providers/box/provider.py

When a folder listing is returned from Box, any folders in the listing
are missing the expected trailing slash.  This is because the folder
metadata method was failing to set the `folder` attribute of child entities.
Fixes: [#OSF-5292]

[CR] box: add slash to materialized attr for folders

---

tests/utils.py
waterbutler/core/provider.py
waterbutler/providers/box/provider.py
waterbutler/providers/cloudfiles/provider.py
waterbutler/providers/dataverse/provider.py
waterbutler/providers/dropbox/provider.py
waterbutler/providers/figshare/provider.py
waterbutler/providers/filesystem/provider.py
waterbutler/providers/github/provider.py
waterbutler/providers/googledrive/provider.py
waterbutler/providers/osfstorage/provider.py
waterbutler/providers/s3/provider.py
waterbutler/server/api/v1/provider/__init__.py

When creating a new folder or uploading a new file in a directory via WaterButler, our conflict-handling heuristics are all over the map. Some providers (osfstorage, S3) allow a file and folder with the same name to coexist in a directory. Others do not, but behave inconsistently when encountering a conflict. For those providers, which ever entity is created first should succeed, and the following request should throw a 409 Conflict. 
Fixes: [#OSF-5226]

[CR] consistently handle file/folder naming conflicts

---

waterbutler/server/api/v1/provider/__init__.py
waterbutler/server/api/v1/provider/movecopy.py

The v1 logging callback for move/copy/rename actions was serializing the
parent of the target, rather than the target itself. Ex.
mv /A/foo.txt /A/B/bar.txt
was sending /A/B/ as dest
should send /A/B/bar.txt as dest
mv /foo.txt /bar.txt
was sending / as dest
should send /bar.txt as dest
This was creating erroneous and confusing log messages on the OSF.
Fixes: [#OSF-5431], [#OFF-68], [#OFF-69], [#OFF-70]

[CR] fix v1 log payload for move/copy/rename dest

---

waterbutler/server/api/v1/provider/__init__.py

v1 was posting the cross-node move/copy logs to the source node's log
endpoint instead of the destination node's.  The OSF infers the
destination from the URL, rather than the payload.  This was causing
actions like `mv /A/foo /B/` to produce a message saying "`A/foo` was
moved to `A/foo`" on A.  Instead we should be logging "`A/foo` was
moved to `B/foo`" on B.
Fixes: [#OSF-5516]

[CR] Fix cross-node logging for v1 move/copy actions

---

tests/providers/s3/test_provider.py
waterbutler/providers/s3/provider.py

A bogus error message in the OSF S3 addon revealed some shenanigans
in how we handle bucket names outside the US (N. Virginia) region.
Amazon permits bucket names that follow subdomain-naming conventions
(labels separated by periods).  WB had been accessing buckets using
the subdomain calling format, which would access a bucket named 'foo'
at `https://foo.s3.amazonaws.com/`.  However, wildcard nested
subdomain certificates are deprecated, and Pythons newer than 2.7.9
will throw a certificate checking error if you try to access them.
IOW a bucket named 'foo' will still work, but a bucket named 'foo.bar'
will try to connect to `https://foo.bar.s3.amazonaws.com/` and
will fail validation.
`boto`, the library WB uses to communicate with S3, supports another
calling format that avoids this …

[CR] s3: support periods in bucketnames for all regions

---

tests/tasks/test_copy.py
tests/tasks/test_move.py
waterbutler/providers/filesystem/provider.py

When running a local dev copy of WB, the modified timestamp returned
from file metadata was for the local time, and lacked an explicit
timezone attachment.  When the file metadata is stored in mongo, mongo
assumes it is Zulu time.  This was causing erroneous and mismatched
modified and created times for osfstorage.
This branch updates filesystem to return a utc datetime with an active
timezone object.  It also updates two tests that weren't being explicit
about their timezone.  Those tests worked fine without the tzinfo, but
we need to start being more disciplined about this.
Fixes: [#OSF-5390]

[CR] fix modified timestamps from filesystem provider

---

tests/tasks/test_copy.py
tests/tasks/test_move.py
waterbutler/constants.py
waterbutler/server/api/v0/core.py
waterbutler/server/api/v0/crud.py
waterbutler/server/api/v1/provider/__init__.py
waterbutler/tasks/copy.py
waterbutler/tasks/move.py

The logging payloads returned by the v0 api have incorrect paths for deleted files and the source files of moves and copies. Currently, moving a file from osfstorage to box results in a source path of `$filename`, instead of `/$file_id`. Deleting a file on ID-using providers results in the path being set to the `materialized_path` instead of `/$file_id`. Moving a file from googledrive to osfstorage results in path being equal to the filename, instead of the full path relative to root.
Fixes: [#OSF-5569]

[CR] fix v0 log paths

---

waterbutler/providers/github/provider.py

[OSF-5838](https://openscience.atlassian.net/browse/OSF-5838)
Make sure move to non-existent folder returns 201 
Return NotFound error when attempting to delete a folder that does not exist
update waterbutler/providers/github/provider.py "def _delete_folder" to return NotFound error when folder to delete does not exist
None
#OSF-5838

[RFR][Feature]OSF-5838 add check for exists before deleting def _delete_folder

---

tests/server/test_utils.py
waterbutler/server/utils.py

Waterbutler was not allowing cross-origin requests as a rule. We want to lessen this restriction some to allow cross-origin requests that are **not** sending cookies but are sending a bearer token.
Add a check in `CORsMixin.set_default_headers` to check if a cross-origin request is being made under the circumstances described above. Add unit tests for the CORsMixin.

Allow non-cookie cross-origin requests

---

tests/server/test_utils.py
waterbutler/server/utils.py

Non-browser clients may or may not set an Origin header when making a
request, but browsers always should.  Don't set ANY CORS headers if
Origin isn't set.  Non-browser clients don't pay attention to CORS, and
a browser that doesn't set Origin should reject the response.

if no Origin header passed, don't set CORS headers

---

tasks.py

`invoke wheelhouse` or `invoke install` will error out when executed from a Dockerfile `RUN` instruction in an attempt to create a Docker image.  This error (build log [attached][0]) prevents the Docker image from being created, so it is a blocker in our environment.
Updating the `wheelhouse` and `install` tasks to **not** allocate a `pty` fixes this issue.
Expose the allocation of a `pty` as an option by the `wheelhouse` and `install` tasks, allowing the allocation of a `pty` to be disabled with `--no-pty` when executing `invoke`.  This will allow the Docker image build to succed.
Adds a `pty` flag to the `install` and `wheelhouse` tasks, defaulting to a value of `True`.  This maintains current behavior.
None.
The build of the Docker image goes smoothly until it is time to run `invoke …

invoke wheelhouse fails building a Docker image when `pty` is `True` 

---

README.md
docs/conf.py
environment.yml
readthedocs.yml

Allow readthedocs.md to build docs for waterbutler despite python 3.5 incompatibility. 
modifies config files so anaconda can work properly with 3.5
https://openscience.atlassian.net/browse/SVCS-101

[SVCS-101] Fix read the docs python 3.5 incompatibility

---

waterbutler/server/api/v1/core.py

[SVCS-2](https://openscience.atlassian.net/browse/SVCS-2)
Don't log expected WaitTimeOutError to Sentry:
Configure Sentry to log WaitTimeOutError at log level INFO
update waterbutler/server/api/v1/core.py class BaseHandler add {'level': 'info'} to WaitTimeOutError catch.
None
[#SVCS-2]

Update handling of WaitTimoutError to log level INFO at Sentry

---

waterbutler/providers/osfstorage/provider.py

This reverts commit b09b786476b8ec6c23436c769e43e246c6482f2c.
Change references the Source Node GUID not the Destination and is breaking archiver OSF tasks.
Tests 🥒  👍

Revert "Update osfstorage intra_{move,copy} to return folder's children"

---

tests/providers/osfstorage/test_provider.py
waterbutler/providers/osfstorage/provider.py

Currently metadata sent back in a response to fangorn after an upload reflects the date modified coming from the file system, not the actual revision metadata from osfstorage.
Updates metadata to return correct info in the response.
https://openscience.atlassian.net/browse/SVCS-259
https://github.com/CenterForOpenScience/osf.io/pull/7155

[SVCS-259] Sends correct date modified in to fangorn after upload

---

waterbutler/providers/osfstorage/provider.py

Currently metadata sent back in a response to fangorn after an upload reflects the date modified coming from the file system, not the actual revision metadata from osfstorage.
Updates metadata to return correct info in the response.
https://openscience.atlassian.net/browse/SVCS-259
https://github.com/CenterForOpenScience/osf.io/pull/7155
https://github.com/CenterForOpenScience/waterbutler/pull/215

[SVCS-259] Sends correct UTC date modified in to fangorn after upload 

---

tests/providers/googledrive/fixtures.py
tests/providers/googledrive/fixtures/sharing.json
tests/providers/googledrive/test_provider.py
waterbutler/providers/googledrive/metadata.py
waterbutler/providers/googledrive/provider.py

https://openscience.atlassian.net/browse/SVCS-273
From the ticket:
> A user reported (see attached pdf) that she has a Google Drive file that shows up in the file browser, but when she clicks on it she gets a "File not found at Google Drive.". The problem is that when getting file metadata for GDocs, we also ask for revision metadata about the file to help construct our metadata response. Under certain permission/sharing conditions, GDrive will return a 403 Not Authorized, which we don't currently handle.
This ticket fixes this issue and cleans up a bunch of issues around Google Drive revision handling.  See the commit messages and docstrings for more details, but the new behaviors are summarized as:
* If a download or metadata request is made without a revision parameter for a file of …

[SVCS-273] support read-only files on GDrive / improve revision handling

---

.travis.yml
README.md
dev-requirements.txt
setup.cfg

Encourage higher unit test coverage by supporting a badging/reporting service to make code coverage metrics more visible to developers.
Specifically, this activates `coveralls.io`, a service that COS has also used for projects such as `ember-osf`.
Here is a sample report that was run against my own personal WB repo. It lets you see code coverage per file, including identifying untested branches of code:
https://coveralls.io/builds/11568940
This does not modify the existing reporting scheme, only the way in which those reports are surfaced to developers during the review / development process. Once we have experimented with these reports we may wish to change how or what is measured.
This requires turning something on at `coveralls.io`, which must be done by someone with write access to …

[proposal] Support use of coveralls.io for repo

---

.gitignore
dev-requirements.txt
setup.cfg
tasks.py
waterbutler/core/metadata.py
waterbutler/core/path.py
waterbutler/core/provider.py
waterbutler/core/streams/file.py
waterbutler/core/streams/http.py
waterbutler/core/streams/json.py
waterbutler/core/streams/zip.py
waterbutler/core/utils.py
waterbutler/providers/box/provider.py
waterbutler/providers/dropbox/provider.py
waterbutler/providers/figshare/path.py
waterbutler/providers/figshare/provider.py
waterbutler/providers/googledrive/provider.py
waterbutler/providers/owncloud/settings.py
waterbutler/providers/s3/provider.py
waterbutler/server/api/v0/core.py
waterbutler/tasks/move.py

:squid: Ready for review, but watch for sea monsters (my first WB PR)
https://openscience.atlassian.net/browse/SVCS-351
- Add type annotations to assist with debugging (core classes and some, but not all, providers)
- Provide an option (currently not on by default) to use mypy, a linter for gradual type hinting- catches weird usages of methods
To try this out, run `inv mypy`. 
In the future this can be used in Travis CI, but is currently hidden behind a flag by default:
`inv test --types`
Many of these types are a "best guess" and subject to evolve in the future. Python types are informational only and do not affect runtime, but tools such as mypy (and pycharm!) support automatic linting to catch errors during development.
I am new to waterbutler. If there is a better type to use, let me …

Add type annotations and mypy compliance

---

setup.py
tests/providers/bitbucket/fixtures.py
tests/providers/bitbucket/fixtures/revisions.json
tests/providers/bitbucket/fixtures/validate_path.json
tests/providers/bitbucket/test_metadata.py
tests/providers/bitbucket/test_path.py
tests/providers/bitbucket/test_provider.py
waterbutler/core/exceptions.py
waterbutler/core/utils.py
waterbutler/providers/bitbucket/__init__.py
waterbutler/providers/bitbucket/metadata.py
waterbutler/providers/bitbucket/path.py
waterbutler/providers/bitbucket/provider.py
waterbutler/providers/bitbucket/settings.py

Add support for a read-only bitbucket provider to WaterButler.
**Feature complete, has passed QA Demo. Still needs code cleanup, tests, documentation.**
_to-come, expect a force-push_
None expected.
[#SVCS-268] - [JIRA](https://openscience.atlassian.net/browse/SVCS-268)
[#SVCS-376] - [JIRA](https://openscience.atlassian.net/browse/SVCS-376)
Entangled with OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/6954

[SVCS-268][SVCS-376] Add readonly provider for Bitbucket

---

waterbutler/providers/googledrive/metadata.py

https://openscience.atlassian.net/browse/SVCS-553
GDrive throws an error when listing the hash for a non-exportable file, this prevents that.
One line fix with comment.
This effects traditional non-exportable files and files with view permissions, but no download permissions.
Hot fix.

[HOTFIX][SVCS-533] Don't error when GDrive file is missing md5sum

---

dev-requirements.txt

No Ticket
* Update `mypy` to `0.560` (the latest)
* `0.511` throws "Name 'builtins' is not defined". Upgrading to the latest version fix this bug.
See Purpose
No
No QA
No special configuration

[No Ticket] Upgrade to `mypy==0.560`

---

dev-requirements.txt

No ticket or ticket to be created
Fix requirement installation by disabling editable install for aiohttpretty. This is the WB counterpart for MFR: https://github.com/CenterForOpenScience/modular-file-renderer/pull/312.
- Remove `-e` from dev requirements, similar to the MFR PR, we don't need such editable install
- Editable install creates a temporary folder which may cause future installation to hang when
`docker-compose up wb_requirements` finds out that the folder already exists and decide to wait for user input. Using `docker-compose up`, no instructions is provided to inform the user what's happening and installation just hangs
- Error message by installing directly inside the container using `invoke install -d`
```bash
Obtaining aiohttpretty from …
```

[No Ticket] Disable editable install for aiohttpretty

---

.gitignore

Adds .python-version to the gitignore file to allow people to use their own pyenv virtual environments without committing those changes.

[] [] Ignore pyenv files

---

tests/providers/googlecloud/fixtures/providers.py
tests/providers/googlecloud/test_provider.py
waterbutler/providers/googlecloud/provider.py

https://openscience.atlassian.net/browse/SVCS-617
Google Cloud Storage API (XML and JSON) only needs the bucket name (and the object name). **Region** is set to the bucket during creation.
For WB, only needs to know which bucket to work on, OSF handles the region and select the correct bucket for WB.
Remove `region` from the provider, tests, docstr and comments.
No
No
No

[SVCS-617] Remove Region From Google Cloud Provider 

---

waterbutler/core/remote_logging.py

https://openscience.atlassian.net/browse/SVCS-818
Improve the process when WB tries to identify requests from MFR render.
Instead of solely relying on a dedicated header which is absent from render calls, WB also checks the referrer.
No
No
No

[SVCS-818] Use referrer to identify MFR render (in addition to the MFR header)

---

waterbutler/auth/osf/handler.py
waterbutler/auth/osf/settings.py

https://openscience.atlassian.net/browse/SVCS-831
Help OSF get more accurate MFR render/export statistics.
When MFR requests metadata from WB, it sets a header identifying itself and indicating the type of MFR action being performed.  This PR will relay that information to the OSF in the authorization request.  This will allow the OSF to distinguish contributor vs. non-contributor views and also avoid missing views due to MFR caching.
None expected.  Will do nothing until SVCS-674 is merged into MFR.
None.
None.

[SVCS-831] signal MFR render/export requests to the OSF

---

tests/auth/osf/test_handler.py
tests/providers/osfstorage/fixtures.py
tests/providers/osfstorage/test_provider.py
tests/server/api/v1/fixtures.py
tests/server/api/v1/test_fuzzing.py
tests/server/api/v1/test_metadata_mixin.py
tests/server/api/v1/utils.py
waterbutler/auth/osf/handler.py
waterbutler/core/auth.py
waterbutler/providers/osfstorage/provider.py
waterbutler/server/api/v1/provider/__init__.py
waterbutler/server/api/v1/provider/metadata.py
waterbutler/server/api/v1/provider/movecopy.py
waterbutler/server/auth.py

https://openscience.atlassian.net/browse/SVCS-892
Cross-region moves in osfstorage are wonky b/c they can't use `intra_move` (which won't copy the data) and they can't use the default `move` (which will create all-new file metadata entries on the OSF, losing guids and versions in the process).   This PR adds an osfstorage-specific `move` method which will both copy the data to the new region and update the file metadata entry on the OSF.
* Factor out duplicate code in osfstorage's `intra_move` and `intra_copy` to make it easier to reason about.  Rewrite associated tests to improve coverage and accuracy.
* Split out the "upload-to-data-storage" and "upload-to-metadata-provider" code from `upload` so that they can be called independently of each other.
* Add an osfstorage-specific `move` …

[WIP][SVCS-892] Support cross-region moves in osfstorage.

---

tests/auth/osf/test_handler.py
waterbutler/auth/osf/handler.py

https://openscience.atlassian.net/browse/PLAT-1310
https://openscience.atlassian.net/browse/PLAT-709
Pass useful useful info for impact metrics back to the waterbutler auth callback so we can count them perfectly.
- adds extra items to payload in auth handler and change test.
Not user-facing
Should be deployed before corresponding OSF PR. https://github.com/CenterForOpenScience/osf.io/pull/8918

[PLAT-1310][PLAT-709] Add more client request info to Impact metrics / Wiki embed metrics

---

requirements.txt
tests/server/api/v1/fixtures.py
tests/server/api/v1/test_core.py
tests/server/api/v1/test_create_mixin.py
tests/server/api/v1/test_metadata_mixin.py
tests/server/api/v1/test_movecopy.py
tests/server/api/v1/test_provider.py
tests/server/api/v1/utils.py
waterbutler/server/app.py

https://openscience.atlassian.net/browse/ENG-374
Upgrade `tornado` from 4.3 to 5.1.1, required for `aiohttp` 0.18->3.5 upgrade
* Updated requirements for tornado5
* Removed redundant reference to `AsyncIOMainLoop`
* Starting 5.0, tornado automatically uses the `asyncio` event loop. See
http://www.tornadoweb.org/en/stable/asyncio.html for detailed info.
* Fixed tests
* `RequestHandler._headers[<header_name>]` returns a byte string in 4.3 but a string in 4.4. This affects tests where we had to do byte-str conversion before/during comparison, which breaks and is no longer needed as well.
* In tornado, setting `debug=True` automatically sets `autoreload=True`. Starting 5.0, `autoreload` breaks WB unit tests where WB's `ProviderHandler` (inherits tornado's `RequestHandler`) is declared as a …

[ENG-374] Upgrade Tornado From 4.3 to 5.1.1

---

tests/providers/bitbucket/fixtures/branch_metadata.json
tests/providers/bitbucket/provider_fixtures.py
tests/providers/bitbucket/test_provider.py
waterbutler/providers/bitbucket/provider.py

No Ticket
The BB API 2.0 `path` endpoint  [/2.0/repositories/{username}/{repo_slug}/src/{node}/{path}](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/src/%7Bnode%7D/%7Bpath%7D) WB uses returns `HTTP 404` if the `{node}` segment is a branch of which the name contains a slash. This is either a limitation or a bug on several BB API 2.0 endpoints, which has nothing to do with encoding. More specifically, neither encoding / with %2F nor enclosing ``node`` with curly braces (%7B and %7D) works.
[Here](https://bitbucket.org/site/master/issues/9969/get-commit-revision-api-does-not-accept) is the closest reference to this issue we have found as of May 2019 and [here](https://github.com/netlify/netlify-cms/issues/2105) is another one …

[No Ticket] Fix The Issue that Branch Name with Slash Breaks BB Repo Endpoints

---

setup.py
tasks.py
tests/providers/box/test_provider.py
waterbutler/providers/box/provider.py

https://openscience.atlassian.net/browse/ENG-313
Throw the box provider into the oath pit. That is, in human-readable English, refactoring the box provider for `aiohttp` 0.18 -> 3.4 upgrade.
- Updated MultiStream and CutoffStream with `__aiter__()` and `__anext__()`
Similar to the fix for OSFStorage/GoogleCloud, both streams must implement the `__anext__()` to properly read the chunk. `CutoffStream` is used for chunked upload (Box, Dropbox, FigShare and Amazon S3). `MultiStream` is inherited by `FormDataStream` (Box contiguous upload), by `JsonStream` (GitHub) and by `ZipLocalFile` (`ZipStreamReader`, DataVerse).
- Removed usage of `self.request()` and context manager
- Before: the provider used `self.request()` and `self.make_request()` interchangeably when making requests; the former …

[OathPit] Throw the Box Provider into OathPit

---

docs/api.rst
tests/providers/github/fixtures/root_provider.json
tests/providers/github/test_provider.py
waterbutler/providers/github/provider.py
waterbutler/providers/github/settings.py

https://openscience.atlassian.net/browse/ENG-444
Improve and consistify GH provider revision-identifying query-parameter support.
* Unify query param handling: the first commit is a re-application of 9b541f2be708, which was reverted in 5fdc63f2d41e.  Updates the provider to support `ref`, `version`, `sha`, and `revision` as commit sha / branch name -identifying parameters.  Also supports `branch` as a branch name-identifying parameter.
* Allow `branch` to be a commit sha. Since the original implementation was written, it was discovered that some queries **are** passing commit shas in the `branch` parameter. Start supporting this.
* Verify sha length in sha vs. branch identifying heuristic.  GH doesn't support abbreviated SHAs, so improve the test by length-testing the sha string …

[FR][ENG-444] improved GitHub revision handling

---

setup.py
tasks.py

https://openscience.atlassian.net/browse/ENG-339
"_Refactor_" the `bitbucket` provider to work with `aiohttp3`.
* NO CHANGE:
* `bitbucket` is a read-only provider and uses `.make_request()` exclusively for its limited number of requests, which works as it is with `aiohttp3` surprisingly as expected.
No
Please refer to the ticket.
No

[ENG-339] [Oath Pit] Throw the Bitbucket provider into the Oath Pit

---

setup.py
tasks.py

https://openscience.atlassian.net/browse/ENG-331
"_Refactor_" the `filesystem` provider to work with `aiohttp3`.
* NO CHANGES:
* `filesystem` is for local develop only, which replaces the `googlecloud` as the storage provider for OSF Storage. No request is made and all are disk access, which works as it is with `aiohttp3`.
No
No
No

[ENG-331] [Oath Pit] Throw the FileSystem provider into the Oath Pit

---

docs/api.rst
tests/providers/github/fixtures/root_provider.json
tests/providers/github/test_exceptions.py
tests/providers/github/test_provider.py
waterbutler/core/provider.py
waterbutler/core/utils.py
waterbutler/providers/bitbucket/provider.py
waterbutler/providers/box/provider.py
waterbutler/providers/cloudfiles/provider.py
waterbutler/providers/dataverse/provider.py
waterbutler/providers/dropbox/provider.py
waterbutler/providers/figshare/provider.py
waterbutler/providers/filesystem/provider.py
waterbutler/providers/github/exceptions.py
waterbutler/providers/github/provider.py
waterbutler/providers/github/settings.py
waterbutler/providers/gitlab/provider.py
waterbutler/providers/googlecloud/provider.py
waterbutler/providers/googledrive/provider.py
waterbutler/providers/onedrive/provider.py
waterbutler/providers/osfstorage/provider.py
waterbutler/providers/owncloud/provider.py
waterbutler/providers/s3/provider.py
waterbutler/tasks/copy.py
waterbutler/tasks/move.py

https://openscience.atlassian.net/browse/ENG-302
This PR replaces https://github.com/CenterForOpenScience/waterbutler/pull/292
h/t to @TomBaxter for the core part implement which is fully functional, I just polished the code
GitHub API has a [rate-limiting](https://developer.github.com/v3/#rate-limiting) feature that only allow 5000 requests per hour. The limit is not a **rate** but a **count**.  To handle this limitation, this PR enables WB to rate-limiting GitHub move/copy requests by allowing 1-2 requests per second.
* GitHub rate-limiting is enforced per user. For example, API requests made to GitHub by non-OSF products users have authorized **count** against the quota.
```
For API requests using Basic Authentication or OAuth, you can make up to 5000 requests
per hour. Authenticated …
```

[ENG-302] Handle GitHub Rate Limiting

---

setup.py
tasks.py
waterbutler/core/provider.py
waterbutler/providers/dropbox/provider.py

https://openscience.atlassian.net/browse/ENG-329
Refactor the `dropbox` provider to work with `aiohttp3`.
* Converted `async with self.request() as resp` to `resp = await self.make_request()`
* Fixed unsafe usage of the `dropbox-api-result` header
* Added a note and TODO for proper usage of `.dropbox_request()` and `.make_request()`
No
Please refer to the ticket, which should be almost (if not exactly) the same as the `box` provider.
No

[ENG-329] [Oath Pit] Throw the Dropbox provider into the Oath Pit

---

setup.py
tasks.py
waterbutler/providers/dataverse/provider.py
waterbutler/providers/dataverse/settings.py

https://openscience.atlassian.net/browse/ENG-328
Enable and update the Dataverse provider for `aiohttp` 3.
* Enabled the provider (including tests)
* Fixed basic auth for request (upload and delete)
-  Please refer to the last part of the updated DocStr for details.
* Updated DocStr and added TODO comments
- General DocStr on different API endpoints used
- General DocStr on `aiohttp.helpersBasicAuth`
- TODO comments to use `X-Dataverse-key` header for download and metadata
- TODO comment to remove unused endpoint
No
No

[ENG-328] [OATHPIT] Throw Dataverse into the Oath Pit

---

setup.py
tasks.py
waterbutler/core/provider.py
waterbutler/providers/owncloud/provider.py
waterbutler/settings.py

https://openscience.atlassian.net/browse/ENG-337
Enable and update the ownCloud provider for `aiohttp` 3.
* WB `.make_request()` now supports WebDAV methods
* `aiohttp.ClientSession` only has functions available for native HTTP methods. For WebDAV (a protocol that extends HTTP) ones, WB lets the `ClientSession` instance call `_request()` directly and then wraps the return object with `aiohttp.client._RequestContextManager`.
</br>
* WB client session now supports customized connector
* For providers that use a customized connector such as owncloud, the new session is created (if no session is found in the event loop) with the given connector while an existing session simply ignores (and closes) the new connector. Given that the session is per loop for each instance, the existing session if …

[ENG-337] [OATHPIT] Throw ownCloud into the Oath Pit

---

setup.py
tasks.py
tests/providers/s3/fixtures.py
tests/providers/s3/test_metadata.py
waterbutler/providers/s3/metadata.py
waterbutler/providers/s3/provider.py

https://openscience.atlassian.net/browse/ENG-338
Enable and update the S3 provider for `aiohttp` 3.
It is unknown why `aiohttp-0.18.x` stores HTTP response header names in all-uppercase (e.g. `'CONTENT-LENGTH'`, `'ETAG'`, etc.). `aiohttp-3.5.x` now uses the more popular title case (e.g. `'Content-Length'`, `'ETAG'`, etc.). This breaks the old implementation for class `S3FileMetadataHeaders` whose calling `self.raw['ETAG']` throws `Key Error`. The class and related tests has been updated.
No
Here is a list of tests that I have done locally, all of which have passed. Extra notes and quirks are added under each list if there is any. In short, S3 behaves as expected.
* Getting metadata for a file and folder
* This is automatic when you list files and expand folders
* Downloading (20B, 1 MB, …

[ENG-338] [OATHPIT] Throw S3 into the Oath Pit

---

setup.py
tasks.py
tests/providers/github/test_provider.py
waterbutler/providers/github/provider.py

https://openscience.atlassian.net/browse/ENG-332
Enable and update the GitHub provider for `aiohttp3`.
* Fix a response release issue for GitHub rate-limiting. In `aiohttp3`, `release()` not only releases the response but also closes the connection. This causes `exception_from_response()` to encounter a connection already closed failure when trying to release or consume the response. The fix: 1) Don't release the response before `calling _rl_handle_forbidden_error()` and 2) Let `_rl_handle_forbidden_error()` and `exception_from_response()` take care of it.
* Fixed mock response header value type in tests: `int` -> `str`. `aiohttpretty` requires the `str` type on both header name and value, which calls `.encode()` on both when building raw headers. Exceptions would be thrown if int header …

[ENG-332] [OATHPIT] Throw GitHub into the Oath Pit

---

setup.py
tasks.py
tests/providers/googledrive/test_provider.py
waterbutler/providers/googledrive/provider.py

https://openscience.atlassian.net/browse/ENG-335
Enable and update the Google Drive provider for `aiohttp3`.
* Simply rewrite `async with ... as resp: ...` into `resp = await ...`.
No
Below is a list of what I have tested locally according to the list provided by the ticket. Surprisingly, everything works as expected.
As usual, 1) files tested are of five different sizes: 20B, 1.4MB, 11MB, 88MB and 264MB, 2) intra-move-copy are tested between two components connected to the same Google account, one component is the Drive root and the other is a Drive folder, and 3) no comments indicates a PASS for each item.
* Getting metadata for a file / folder: tested along with file view and folder listing
* Downloading
* Uploading (both to the root and a subfolder
* One file
* Multiple files
* …

[ENG-335] [OATHPIT] Throw Google Drive into the Oath Pit

---

setup.py
tasks.py

https://openscience.atlassian.net/browse/ENG-336
Enable and update the OneDrive provider for `aiohttp3`.
No changes 🔥 🔥 🔥 
N / A
Fixed move / copy which is broken on both `staging` and `prod`.
As usual, no comments indicates a **PASS**. Please test both **OneDrive root** and **OneDrive folder** as OSF project root.
* Getting metadata for a file / folder: tested along folder listing and file rendering
* Downloading
* Uploading: N / A
* DAZ
* Deleting: N / A
* Folder
* Creation: N / A
* Upload: tested along with **Uploading**
* Deletion: N / A
* Rename files and folders: N / A
* Verifying non-root folder access for id-based folders: Yes and tested
* Intra move / copy: N / A
* Inter move / copy (light testing only)
* One and multiple files
* One and multiple folders
* From OneDrive to …

[ENG-336] [OATHPIT] Throw OneDrive into the Oath Pit

---

setup.py
tasks.py
tests/providers/figshare/fixtures/root_provider.json
tests/providers/figshare/test_metadata.py
tests/providers/figshare/test_provider.py
waterbutler/core/provider.py
waterbutler/providers/figshare/metadata.py
waterbutler/providers/figshare/provider.py

https://openscience.atlassian.net/browse/ENG-330
Enable and update the figshare provider for `aiohttp3`.
The figshare provider directly calls `aiohttp.request()` in `aiohttp` 0.18 for some downloads, which no longer works with `aiohttp-3.5`. Instead, use the updated `super().make_request()`. However, this only partially fix the download issue.
To fully fix the download issue, the figshare auth header are dropped for published / public files.
* As for the figshare provider: When a file has been published, the figshare download request returns a redirection URL which downloads the file directly from its backend storage S3. The new request does not need any auth at all. More importantly, the default figshare auth header breaks the download since S3 API does not understand figshare API. Thus, …

[ENG-330] [OATHPIT] Throw figshare into the Oath Pit

---

dev-requirements.txt
setup.py
tasks.py
tests/providers/gitlab/fixtures.py
tests/providers/gitlab/test_provider.py
waterbutler/providers/gitlab/provider.py

https://openscience.atlassian.net/browse/ENG-333
Enable and update the GitLab provider for `aiohttp3`.
* Fixed download and its tests
* This provider has been using a complicated hack for download due to [GL-Issue#31470](https://gitlab.com/gitlab-org/gitlab-ce/issues/31470) which breaks the dedicated endpoint for direct raw file download. Fortunately, the bug was fixed in GL API 10.0 so that download has been re-written to use the preferred and intuitive approach.
* Another reason for the re-writing is that the work-around would not work with `aiohttp3` even if we kept it for backward compatibility. It needs to modify response headers directly within the object before passing it to the response stream reader. However, `aiohttp3` makes it impossible: the `headers` is defined as a `@reify` …

[ENG-333] [OATHPIT] Throw GitLab into the Oath Pit

---

setup.py
tasks.py
tests/providers/cloudfiles/test_metadata.py
tests/providers/cloudfiles/test_provider.py
waterbutler/providers/cloudfiles/provider.py

https://openscience.atlassian.net/browse/ENG-327
Enable and update the CloudFiles provider for `aiohttp3`.
* Removed context manager when making request
* Improved import style
* Fixed import and usage for `multidict`
* Remove unused imports and improve style
* Fixed JSON response parsing
* Removed `--ignore` for `pytest` since all providers have been converted
N / A
N / A
CloudFiles was the original storage provider for OSFStorage which has been deprecated since early 2018. It is only not testable by QA.
No

[ENG-327] [OATHPIT] Throw CloudFiles into the Oath Pit

---

requirements.txt
tests/core/test_utils.py
waterbutler/core/utils.py
waterbutler/server/app.py
waterbutler/tasks/app.py

https://openscience.atlassian.net/browse/ENG-1393
Ticket [ENG-481](https://openscience.atlassian.net/browse/ENG-481) with [PR #387](https://github.com/CenterForOpenScience/waterbutler/pull/387) introduced a slight side-effect when `raven-python` was replaced by `sentry-sdk`. Logging messages at error level and above are now sent to Sentry as events by default. We’d love to change this back to it’s original behavior: only exceptions are sent.
* Disabled any level of logs being sent as event 
* Bumped the `sentry-sdk` from version `0.13.2` to `0.14.0`.
* Improved tests for `async_retry`
* Improved `import` style on touched files
N / A
N / A
Monitor COS Sentry on staging3 (OATHPIT) after merge
N / A

[ENG-1393] Fix Sentry events due to `raven-python` -> `sentry-sdk`

---

waterbutler/providers/s3/provider.py

We decided to move away from using parent directory names as bucket identifiers to delineating them with a colon. This is for two reasons:
- It looks better
- It allows the folder_id received to always be the same as the one sent.
- simply parses the settings `id` with a colon.
- was discovered by QA test: https://github.com/CenterForOpenScience/osf-selenium-tests/blob/f9089d5b3db7673cf961e2874e955ddd93631936/api/osf_api.py#L406
- here's a script I ran to replicate that test locally:
```python
attributes = requests.get(
f'http://0.0.0.0:8000/v2/nodes/{node_id}/addons/s3/folders/',
headers={'Authorization': f'Bearer {token}'}
).json()['data'][0]['attributes']
raw_payload = {
'data': {
'type': 'node_addons',
'id': 's3',
'attributes': {
'folder_id': …
```

Use colon delineation for s3 buckets

---

tests/providers/s3/fixtures.py
tests/providers/s3/test_provider.py
waterbutler/providers/s3/metadata.py
waterbutler/providers/s3/provider.py

Ensure relative paths work properly for s3.

[S3 Improvements] More WB Path Fixes

---

tests/providers/s3/fixtures.py
tests/providers/s3/test_provider.py
waterbutler/providers/s3/metadata.py
waterbutler/providers/s3/provider.py

Enables WB to support both bucket-root and subfolder-root configuration for S3.
Credit @Johnetordoff for all the work 👍 
Project notion: https://www.notion.so/cos/S3-improvements-476a5b07cb7e4f458e9cd4c77cfa03ec
OSF Part: https://github.com/CenterForOpenScience/osf.io/pull/10416
* Enables WB to support both bucket-root and subfolder-root configuration for S3
* Updated WB to support `:/` as the new delimiter for S3 bucket
* Added/Updated unit tests
* Deployment requires downtime, must be deployed at the same time as [OSF](https://github.com/CenterForOpenScience/osf.io/pull/10416)
* For details, see our release playbook (TBD)
Here are all child PRs that have been merged into this feature branch.
- Unit tests: https://github.com/CenterForOpenScience/waterbutler/pull/408
- Clean-up: …

[ENG-4624] [S3 Improvements] Project PR - Waterbutler Part

---

waterbutler/core/utils.py

with gravyvalet active, "name" is opaque id for a specific addon instance and osf puts the provider name in settings['service'] -- let that work

support auth.settings.service from osf

---

dev-requirements.txt
doc-requirements.txt

[ENG-7523]
- Pin dependencies in doc-requirements.txt to specific versions compatible with python3.13
- Pin test related dependencies in dev-requirements.txt to newer versions where applicable
- Add version numbers to doc-requirements.txt
- Bump versions for pytest, pytest-asyncio
[ENG-7523]: https://openscience.atlassian.net/browse/ENG-7523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-7523] Pin versions in doc-requirements.txt

---

waterbutler/auth/osf/handler.py
waterbutler/core/utils.py
waterbutler/server/api/v1/provider/__init__.py
waterbutler/server/api/v1/provider/create.py

https://openscience.atlassian.net/browse/ENG-7847
WB cant seem to read file uploads from tornado. Fix that!
Change  `async def prepare_stream(self):`   `async def data_received(self, chunk)` write/read stream logic to make it possible to work with python 3.13
https://github.com/user-attachments/assets/f3ddb9e3-4f31-41c1-88b2-e4ba2a697e70
It looks like a low level code changings so maybe there is more explicit way to do it to keep it more clear.

[ENG-7847] 2.4.4: BE: Fix broken upload reads in WB for python 3.13

---

tests/providers/s3/fixtures.py
tests/providers/s3/test_provider.py
waterbutler/providers/s3/provider.py

https://openscience.atlassian.net/browse/ENG-7981
Throughout the s3 PR you are using the boto3 client to make HTTP request calls. This bypasses WB's interface for making requests, waterbutler.core.provider.ProviderBase.make_request . We have a bunch of code in make_request to handle retries, error construction, header manipulation, etc.  All that functionality would need to be duplicated just for s3 alone.  It would be better if we could use boto3's ability to generate signed urls that we can pass to make_request.  Having one way of doing requests makes it easier to maintain, troubleshoot, and reason about request issues in WB. Every other provider goes through make_request (though some wrap it with additional provider-specific behavior), and it would be good for s3 to do so as well. …

[ENG-7981]Use generic make request if possible for s3

---

tests/core/test_utils.py
tests/providers/dataverse/test_provider.py
tests/providers/figshare/test_metadata.py
tests/providers/figshare/test_provider.py
tests/providers/gitlab/test_provider.py
tests/providers/s3/fixtures.py
tests/providers/s3/test_provider.py
tests/server/api/v1/test_create_mixin.py
waterbutler/auth/osf/handler.py
waterbutler/core/streams/__init__.py
waterbutler/core/streams/http.py
waterbutler/providers/dataverse/provider.py
waterbutler/providers/s3/metadata.py
waterbutler/providers/s3/provider.py

https://openscience.atlassian.net/browse/ENG-8054
WB has a bunch of failing tests. Let's fix 'em!
If the cause of a test failure turns out to need a big fix, we can create another ticket to track it.
Changing unit testing to be passed for 3.13 python (create the branch from the following PR branch to keep changings
https://github.com/CenterForOpenScience/waterbutler/pull/434
)
1. Hard to deal with S3 unittesting from my side (maybe it is somehow related with M1 Max chip so I am not really confident about , so it is weird), for example  `await provider._check_region()` stuck for my though on meeting session the execution flow goes further from Fitz side ).
2. 
while trying to run tests separately they are passed .
python -m poetry run pytest …

[ENG-8054] Check and rewrite unittesting where is needed

---

tests/server/api/v1/test_create_mixin.py
tests/server/api/v1/utils.py

[ENG-8229]
- Address warning that is gumming up the test logs
- Remove `mock_handler.uploader` which uses `AsyncMock` from generic `mock_handler` util
- Add back `uploader` only to test that needs it
- `mock_handler.uploader` is no longer accessible in other tests that are using `mock_handler`
[ENG-8229]: https://openscience.atlassian.net/browse/ENG-8229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-8229] Address warning re: AsyncMockMixin not being awaited

---

waterbutler/providers/dropbox/provider.py

on coping from bitbucket to dropbox (suppose it may be common for all providers)
https://openscience.atlassian.net/browse/ENG-8404
Fix coping file from bitbucket to dropbox
`waterbutler.core.exceptions.MetadataError: 400, {"response": "Error in call to API function \"files/get_metadata\": request body: path: '.gitignore' did not match pattern '(/(.|[\\r\\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'"}`
adding / at the path beginning if it is not set before `self.make_request` call to avoid possible errors 
Maybe there is additional use cases where the condition is needed to be added too or do it more generic all over providers

[ENG-8404] path is needed to be started with '/' 

---

tests/providers/s3/test_provider.py
tests/tasks/conftest.py
tests/utils.py
waterbutler/providers/s3/provider.py
waterbutler/server/api/v0/core.py
waterbutler/server/api/v1/core.py

https://openscience.atlassian.net/browse/ENG-8558
We merged the WB feature branch to MFR, letting a few minor issues pass. Let’s revisit the CR and address those. I will create a feature/post-buff-worms based on develop for you to target your PR.
Have gone through the ticket WB update ticket comments
https://github.com/CenterForOpenScience/waterbutler/pull/463
and updated stuff that is explicit to resolve, 
for some non explicit stuff like some S3 possible post-release updates/investigation left comments 
https://github.com/CenterForOpenScience/waterbutler/pull/463#discussion_r2264018047
https://github.com/CenterForOpenScience/waterbutler/pull/463#discussion_r2264041336

[ENG-8558] update WB stuff that is explicit to resolve
